module.exports = {
	DEFAULT_CHAT: "DEFAULT_CHAT",
	USER_CONNECTED: "USER_CONNECTED",
	MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
	SEND_MESSAGE: "SEND_MESSAGE",
	RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
	USER_DISCONNECTED: "USER_DISCONNECTED",
	TYPING: "TYPING",
	VERIFY_USER: "VERIFY_USER",
	LOGOUT: "LOGOUT",
	NEW_CHAT_USER: "NEW_CHAT_USER",
	NEW_CHAT: "NEW_CHAT",
	UPDATE_CHATS: "UPDATE_CHATS"
}