module.exports = {
	DEFAULT_CHAT: "DEFAULT_CHAT",
	USER_CONNECTED: "USER_CONNECTED",
	MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
	CREATE_NEW_MESSAGE: "CREATE_NEW_MESSAGE",
	RECIEVE_MESSAGE: "RECIEVE_MESSAGE",
	USER_DISCONNECTED: "USER_DISCONNECTED",
	TYPING: "TYPING",
	VERIFY_USER: "VERIFY_USER",
	LOGOUT: "LOGOUT",
	CREATE_NEW_CHAT_USER: "CREATE_NEW_CHAT_USER",
	CREATE_NEW_CHAT: "CREATE_NEW_CHAT",
	NEW_CHAT_CREATED: "NEW_CHAT_CREATED",
	UPDATE_CHATS: "UPDATE_CHATS",
	ADD_USER_TO_CHAT:"ADD_USER_TO_CHAT"
}